#############################################################################
# Makefile for building: libdmrt.so.1.0.0
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Nov 12 13:00:12 2015
# Project:  ../dmrt/dmrt.pro
# Template: lib
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = gcc
DEFINES       = -DQT_WEBKIT
CFLAGS        = -m64 -pipe -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -Wall -Wextra -pedantic -fPIC -shared -fopenmp -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I./dmrt -I/home/rottee/Python/include/python2.7
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -shared -Wl,-soname,libdmrt.so.1
LIBS          = $(SUBLIBS)   -L/home/rottee/Python/lib/python2.7 -lpython2.7 -lgomp 
AR            = ar cqs
RANLIB        = 
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ./dmrt/dmrtalg.cpp \
		./dmrt/dmrtalg2.cpp \
		./dmrt/dmrtreader.cpp \
		./dmrt/dmrtmain.cpp \
		./dmrt/libdmrt.cpp 
		
OBJECTS       = dmrtalg.o \
		dmrtalg2.o \
		dmrtreader.o \
		dmrtmain.o \
		libdmrt.o
		
TARGET        = libdmrt.so.1.0.0
TARGETA       = libdmrt.a
TARGETD       = libdmrt.so.1.0.0
TARGET0       = libdmrt.so
TARGET1       = libdmrt.so.1
TARGET2       = libdmrt.so.1.0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)


staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)
dist: 
	@$(CHK_DIR_EXISTS) .tmp/dmrt1.0.0 || $(MKDIR) .tmp/dmrt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/dmrt1.0.0/ && (cd `dirname .tmp/dmrt1.0.0` && $(TAR) dmrt1.0.0.tar dmrt1.0.0 && $(COMPRESS) dmrt1.0.0.tar) && $(MOVE) `dirname .tmp/dmrt1.0.0`/dmrt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/dmrt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

dmrtalg.o: ./dmrt/dmrtalg.cpp ./dmrt/dmrtalg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dmrtalg.o ./dmrt/dmrtalg.cpp

dmrtalg2.o: ./dmrt/dmrtalg2.cpp ./dmrt/dmrtalg2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dmrtalg2.o ./dmrt/dmrtalg2.cpp

dmrtreader.o: ./dmrt/dmrtreader.cpp ./dmrt/dmrtreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dmrtreader.o ./dmrt/dmrtreader.cpp

dmrtmain.o: ./dmrt/dmrtmain.cpp ./dmrt/dmrtmain.h \
		./dmrt/dmrtalg.h \
		./dmrt/dmrtreader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dmrtmain.o ./dmrt/dmrtmain.cpp

libdmrt.o: ./dmrt/libdmrt.cpp ./dmrt/dmrtmain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o libdmrt.o ./dmrt/libdmrt.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/dmrt/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/dmrt/bin/ 
	-$(INSTALL_PROGRAM) "$(TARGET)" "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET0)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET1)"
	-$(SYMLINK) "$(TARGET)" "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET2)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET0)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET1)" 
	 -$(DEL_FILE) "$(INSTALL_ROOT)/opt/dmrt/bin/$(TARGET2)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/dmrt/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

